### ISSUE TITLE
[ToDo] - 15/abr

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/web-scraping-js#9]
- [ ] Separação do código em arquivos diferentes {responsabilidade única}
- [ ] Formato do objeto: alterar nome das chaves e tipagens específicas de cada variável
- [ ] Salvar arquivos .xls em uma pasta em específico
- [ ] Definir uma lógica para o nome do arquivo .xls com base nos inputs de busca
- [ ] Criar um README.md explicativo
